name: Test Frontend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

defaults:
  run:
    working-directory: packages/frontend

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Uncomment when frontend has lint script configured
      # - name: Run lint
      #   run: npm run lint

      # Uncomment when frontend has type-check script configured
      # - name: Run type check
      #   run: npm run type-check

      # Uncomment when frontend has tests configured
      # - name: Run tests
      #   run: npm run test

      - name: Build frontend
        run: npm run build

      # Optional: Upload build artifacts
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: frontend-build
      #     path: packages/frontend/dist
      #     retention-days: 7
